# Generated by Django 3.2.12 on 2022-07-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
    ]
